#!/usr/bin/env ruby

print "Digite o nome do arquivo de entrada:"
file_name = gets.chomp + ".pgm"

puts """
Arquivo #{file_name} carregado com sucesso.
c - carga
t - exibicao na tela
n - negativo
r - rotacao
v - espelhamento vertical
h - espelhamento horizontal
x - corte
e - filtro da erosao
d - filtro da dilatacao
m - filtro da mediana
z - filtro da media
1 - filtro de bordas 1
2 - filtro de bordas 2
3 - filtro de bordas 3
g - gravacao
C - comparacao
a - ajuda
s - sair
"""

begin
  print "Digite um comando:"
  command = gets
  case command
  when "t\n"
    puts
    puts File.read(file_name)
  when "s\n"
    break
  end
end while command